@rootApi = http://localhost:9003/api/v1

#### server test

GET http://localhost:9003

###
POST http://localhost:9003/api/v1/users
Content-Type: application/json

{
    "fName": "Anil",
    "lName": "Khand"
    "email": "anil@gmail.com",
    "password": "hello",
    "phone":"0452348839"
}
